version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run cmd/app.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/paintcalculator
    ports:
      - "8080:8080"